/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Classes.TerminalConsultas;
/**
 *
 * @author Nozawa
 */
public class UIMédico extends javax.swing.JFrame {
    private TerminalConsultas terminalConsultas;
    /**
     * Creates new form UIMédico
     */
    public UIMédico(TerminalConsultas terminalConsultas) {
        initComponents();
        this.terminalConsultas = terminalConsultas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCriarDiagnostico = new javax.swing.JMenuItem();
        itemAssociarAlergia = new javax.swing.JMenuItem();
        itemVerificarExames = new javax.swing.JMenuItem();
        itemVerificarAlergias = new javax.swing.JMenuItem();
        itemHistoricoConsultas = new javax.swing.JMenuItem();
        itemReceitasValidas = new javax.swing.JMenuItem();

        jMenu1.setText("Consulta");

        itemCriarDiagnostico.setText("Criar Diagnóstico");
        itemCriarDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCriarDiagnosticoActionPerformed(evt);
            }
        });
        jMenu1.add(itemCriarDiagnostico);

        itemAssociarAlergia.setText("Associar Alergia");
        itemAssociarAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAssociarAlergiaActionPerformed(evt);
            }
        });
        jMenu1.add(itemAssociarAlergia);

        itemVerificarExames.setText("Exibir Exames");
        itemVerificarExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerificarExamesActionPerformed(evt);
            }
        });
        jMenu1.add(itemVerificarExames);

        itemVerificarAlergias.setText("Exibir Alergias");
        itemVerificarAlergias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerificarAlergiasActionPerformed(evt);
            }
        });
        jMenu1.add(itemVerificarAlergias);

        itemHistoricoConsultas.setText("Histórico de consultas");
        itemHistoricoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistoricoConsultasActionPerformed(evt);
            }
        });
        jMenu1.add(itemHistoricoConsultas);

        itemReceitasValidas.setText("Receitas ainda válidas");
        itemReceitasValidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReceitasValidasActionPerformed(evt);
            }
        });
        jMenu1.add(itemReceitasValidas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCriarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCriarDiagnosticoActionPerformed
        UIDiagnóstico ui = new UIDiagnóstico(terminalConsultas, this);
        ui.setVisible(true);
    }//GEN-LAST:event_itemCriarDiagnosticoActionPerformed

    private void itemAssociarAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAssociarAlergiaActionPerformed
        UIAlergia ui = new UIAlergia(terminalConsultas);
        ui.setVisible(true);
    }//GEN-LAST:event_itemAssociarAlergiaActionPerformed

    private void itemVerificarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerificarExamesActionPerformed
        UIData ui = new UIData(terminalConsultas, "verificarExames");
        ui.setVisible(true);
    }//GEN-LAST:event_itemVerificarExamesActionPerformed

    private void itemVerificarAlergiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerificarAlergiasActionPerformed
        UIRelatório ui = new UIRelatório("Alergias", terminalConsultas.exibirAlergias());
        ui.setVisible(true);
    }//GEN-LAST:event_itemVerificarAlergiasActionPerformed

    private void itemReceitasValidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReceitasValidasActionPerformed
        UIRelatório ui = new UIRelatório("Receitas ainda válidas", terminalConsultas.exibirReceitasVálidas());
        ui.setVisible(true);
    }//GEN-LAST:event_itemReceitasValidasActionPerformed

    private void itemHistoricoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistoricoConsultasActionPerformed
        UIRelatório ui = new UIRelatório("Histórico do paciente", terminalConsultas.exibirHistóricoPaciente());
        ui.setVisible(true);
    }//GEN-LAST:event_itemHistoricoConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIMédico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UIMédico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAssociarAlergia;
    private javax.swing.JMenuItem itemCriarDiagnostico;
    private javax.swing.JMenuItem itemHistoricoConsultas;
    private javax.swing.JMenuItem itemReceitasValidas;
    private javax.swing.JMenuItem itemVerificarAlergias;
    private javax.swing.JMenuItem itemVerificarExames;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
