/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Classes.TerminalConsultas;
import Classes.Clínica;
/**
 *
 * @author Nozawa
 */
public class UIPrincipal extends javax.swing.JFrame {
    private TerminalConsultas terminalConsultas = new TerminalConsultas();
    /**
     * Creates new form inicio
     */
    public UIPrincipal() {
        initComponents();
        Clínica clínica = new Clínica();
        terminalConsultas = clínica.iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        labelStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMedico = new javax.swing.JMenu();
        itemAutenticarMédico = new javax.swing.JMenuItem();
        itemProximaConsulta = new javax.swing.JMenuItem();
        itemDoençasMaisFrequentes = new javax.swing.JMenuItem();
        menuSecretario = new javax.swing.JMenu();
        itemAutenticarSecretário = new javax.swing.JMenuItem();
        itemNovaConsulta = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMedico.setText("Médico");

        itemAutenticarMédico.setText("Autenticar médico");
        itemAutenticarMédico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutenticarMédicoActionPerformed(evt);
            }
        });
        menuMedico.add(itemAutenticarMédico);

        itemProximaConsulta.setText("Próxima consulta");
        itemProximaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProximaConsultaActionPerformed(evt);
            }
        });
        menuMedico.add(itemProximaConsulta);

        itemDoençasMaisFrequentes.setText("Verificar doenças mais frequentes");
        itemDoençasMaisFrequentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDoençasMaisFrequentesActionPerformed(evt);
            }
        });
        menuMedico.add(itemDoençasMaisFrequentes);

        jMenuBar1.add(menuMedico);

        menuSecretario.setText("Secretário");

        itemAutenticarSecretário.setText("Autenticar secretário");
        itemAutenticarSecretário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutenticarSecretárioActionPerformed(evt);
            }
        });
        menuSecretario.add(itemAutenticarSecretário);

        itemNovaConsulta.setText("Criar nova consulta");
        itemNovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNovaConsultaActionPerformed(evt);
            }
        });
        menuSecretario.add(itemNovaConsulta);

        jMenuBar1.add(menuSecretario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //operações de médico
    private void itemAutenticarMédicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutenticarMédicoActionPerformed
        UIAutenticação ui = new UIAutenticação(terminalConsultas, "médico");
        ui.setVisible(true);
    }//GEN-LAST:event_itemAutenticarMédicoActionPerformed
    //operações de secretário
    private void itemAutenticarSecretárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutenticarSecretárioActionPerformed
        UIAutenticação ui = new UIAutenticação(terminalConsultas, "secretário");
        ui.setVisible(true);
    }//GEN-LAST:event_itemAutenticarSecretárioActionPerformed

    private void itemNovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovaConsultaActionPerformed
        UIConsulta uiConsulta = new UIConsulta(terminalConsultas);
        uiConsulta.setVisible(true);
    }//GEN-LAST:event_itemNovaConsultaActionPerformed

    private void itemProximaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProximaConsultaActionPerformed
        if(terminalConsultas.próximaConsulta()){
            UIMédico ui = new UIMédico(terminalConsultas);
            ui.setVisible(true);
        }else{
            labelStatus.setText("Sem consultas!");
        }
    }//GEN-LAST:event_itemProximaConsultaActionPerformed

    private void itemDoençasMaisFrequentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDoençasMaisFrequentesActionPerformed
        UIData ui = new UIData(terminalConsultas, "doencasMaisFrequentes");
        ui.setVisible(true);
    }//GEN-LAST:event_itemDoençasMaisFrequentesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAutenticarMédico;
    private javax.swing.JMenuItem itemAutenticarSecretário;
    private javax.swing.JMenuItem itemDoençasMaisFrequentes;
    private javax.swing.JMenuItem itemNovaConsulta;
    private javax.swing.JMenuItem itemProximaConsulta;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JMenu menuMedico;
    private javax.swing.JMenu menuSecretario;
    // End of variables declaration//GEN-END:variables
}
